// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PersonalBlogAPI.Data;

#nullable disable

namespace PersonalBlogAPI.Migrations
{
    [DbContext(typeof(BlogDbContext))]
    [Migration("20251209140657_BlogDetails")]
    partial class BlogDetails
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("PersonalBlogAPI.Model.Blog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Content")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Blogs");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Content = "This post explains the basics of C# programming.",
                            Title = "Introduction to C#"
                        },
                        new
                        {
                            Id = 2,
                            Content = "Learn how to build web applications using ASP.NET.",
                            Title = "Working with ASP.NET"
                        },
                        new
                        {
                            Id = 3,
                            Content = "A guide to using EF Core for data access in .NET applications.",
                            Title = "Entity Framework Core"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
